<?php @session_start();require_once('../db_2_js.class.php');require_once('../../class/Bee.class.php');require_once('../../class/default.class.php');$Beclas->checkIns();if(!empty($_POST['user'])AND!empty($_POST['nivo'])){$user=explode(" HHH ",$_POST['user']);$nivo=explode(" HHH ",$_POST['nivo']);$nbr_pseudo=$tams->prepare("SELECT COUNT(id_cha) nbr FROM achat
		     WHERE pseudo_cha=:pse AND codenamepack_cha=:pse2 ");$nbr_pseudo->execute(array('pse'=>$user[1],'pse2'=>$nivo[1]));$chif_pse=$nbr_pseudo->fetch();if($chif_pse['nbr']==0){$req=$tams->prepare('INSERT INTO achat  (idtransaction, iduser_cha, pseudo_cha, idpack_cha, codenbrpack, codenamepack_cha, nompack_cha, prixpack_cha, methodpaie_cha, statu_cha, datapai_cha, theme_cha, datephp_cha, datesql_cha ) 
								VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,NOW()) ');$inser=$req->execute(array(100001,$user[0],$user[1],$nivo[0],$nivo[2],$nivo[1],$nivo[3],$nivo[4],"ADMIN_TABLEAU_DE_BORD_WEB",1,"100001 HHH ".$user[0]." HHH ".$user[1]." HHH codeuser HHH email HHH 0 HHH 0 HHH ".$nivo[0]." HHH ".$nivo[2]." HHH ".$nivo[1]." HHH ".$nivo[3]." HHH ".$nivo[4]." HHH ADMIN HHH ADMIN",'',$Beclas->phpDate()));if($inser){$ParainDirect="";$ParainInDirect="";$buyPack=$nivo[3];$ligne=$tams->prepare("SELECT * FROM _webapp_info
                                      WHERE id=:pse  ");$ligne->execute(array('pse'=>1));$ligneAll=$ligne->fetch();$costParainDirect=$ligneAll['pdirect'];$costParainInDirect=$ligneAll['pindirect'];$fraiPaiement=$ligneAll['frai_paie_mobile'];$money=intval($nivo[4]);$infoUser=$tams->prepare("SELECT * FROM user
                                      WHERE pseudo=:pse  ");$infoUser->execute(array('pse'=>$user[1]));$infoUserAll=$infoUser->fetch();$ParainDirect=$infoUserAll['parrain'];if(!empty($ParainDirect)){$infoParDir=$tams->prepare("SELECT * FROM user
										  WHERE pseudo=:pse  ");$infoParDir->execute(array('pse'=>$ParainDirect));$infoParDirAll=$infoParDir->fetch();$ParainInDirect=$infoParDirAll['parrain'];}if(!empty($ParainDirect)AND!empty($ParainInDirect)){$userPD=$ParainDirect;$MoneyParainDirect=$costParainDirect*$money/100;$blocA=$tams->query(" SELECT * FROM  user_bonus  WHERE user_bnk='$userPD'  ");$outils=array();while($outilA=$blocA->fetch()){$solde=$outilA["amount_bnk"]+$MoneyParainDirect;$stmt=$tams->prepare("UPDATE user_bonus SET  amount_bnk=$solde  WHERE user_bnk='$userPD' ");$upd=$stmt->execute();$req=$tams->prepare('INSERT INTO user_notification  (id_user_noti,	lu_noti,	suj_noti,	desc_noti, someout_noti, somenew_noti, phpdate_noti,	sqldate_noti ) 
                                                        VALUES (?,?,?,?,?,?,?,NOW()) ');$inser=$req->execute(array($outilA["id_user_bnk"],0,"Bonus","Vous avez réçus: RSOLDE, suite l\'achat du pack (".$buyPack.") par l'utilisateur: ".$user[1].", Nouveau solde bonus: NSOLDE",$MoneyParainDirect,$solde,$Beclas->phpDate()));}$userPD2=$ParainInDirect;$MoneyParainInDirect=$costParainInDirect*$money/100;$MoneyDesParain=$MoneyParainDirect+$MoneyParainInDirect;$MoneyFacop=$money-$MoneyDesParain;$blocA=$tams->query(" SELECT * FROM  user_bonus  WHERE user_bnk='$userPD2'  ");$outils=array();while($outilA=$blocA->fetch()){$solde2=$outilA["amount_bnk"]+$MoneyParainInDirect;$stmt=$tams->prepare("UPDATE user_bonus SET  amount_bnk=$solde2  WHERE user_bnk='$userPD2' ");$upd=$stmt->execute();$req=$tams->prepare('INSERT INTO user_notification  (id_user_noti,	lu_noti,	suj_noti,	desc_noti, someout_noti, somenew_noti,	phpdate_noti,	sqldate_noti ) 
                                                          VALUES (?,?,?,?,?,?,?,NOW()) ');$inser=$req->execute(array($outilA["id_user_bnk"],0,"Bonus","Vous avez réçus: RSOLDE, suite l\'achat du pack (".$buyPack.") par l'utilisateur: ".$user[1].", Nouveau solde bonus: NSOLDE",$MoneyParainInDirect,$solde2,$Beclas->phpDate()));}$req=$tams->prepare('INSERT INTO _admin_bank  (some_bk, somepd_bk, somepi_bk, pack_bk, user_bk,	padirect_bk,	paindirect_bk,	datephp_bk,	datesql_bk ) 
                                                VALUES (?,?,?,?,?,?,?,?,NOW()) ');$inser=$req->execute(array($MoneyFacop,$MoneyParainDirect,$MoneyParainInDirect,$buyPack,$user[1],$ParainDirect,$ParainInDirect,$Beclas->phpDate()));$req=$tams->prepare('INSERT INTO _admin_historique_user (id_hu, user, emai, ip ,type, messag,lu,dates ) 
                                                VALUES (?,?,?,?,?,?,?,NOW()) ');$inser=$req->execute(array($user[0],$ParainDirect,$ParainInDirect,$_SERVER["REMOTE_ADDR"],"ACHAT PACK",$user[1].", a acheté le pack (".$buyPack."). Parrain direct:".$ParainDirect.". Parrain indirect:".$ParainInDirect." _(TABLEAU BORD)",0));$result="true";}else if(!empty($ParainDirect)){$userPD=$ParainDirect;$MoneyParainDirect=$costParainDirect*$money/100;$MoneyFacop=$money-$MoneyParainDirect;$blocA=$tams->query(" SELECT * FROM  user_bonus  WHERE user_bnk='$userPD'  ");$outils=array();while($outilA=$blocA->fetch()){$solde=$outilA["amount_bnk"]+$MoneyParainDirect;$stmt=$tams->prepare("UPDATE user_bonus SET  amount_bnk=$solde  WHERE user_bnk='$userPD' ");$upd=$stmt->execute();$req=$tams->prepare('INSERT INTO user_notification  (id_user_noti,	lu_noti,	suj_noti,	desc_noti, someout_noti, somenew_noti,	phpdate_noti,	sqldate_noti ) 
                                                          VALUES (?,?,?,?,?,?,?,NOW()) ');$inser=$req->execute(array($outilA["id_user_bnk"],0,"Bonus","Vous avez réçus: RSOLDE, suite l\'achat du pack (".$buyPack.") par l'utilisateur: ".$user[1].", Nouveau solde bonus: NSOLDE",$MoneyParainDirect,$solde,$Beclas->phpDate()));}$req=$tams->prepare('INSERT INTO _admin_bank  (some_bk, somepd_bk, somepi_bk, pack_bk, user_bk,	padirect_bk,	paindirect_bk,	datephp_bk,	datesql_bk ) 
                                                VALUES (?,?,?,?,?,?,?,?,NOW()) ');$inser=$req->execute(array($MoneyFacop,$MoneyParainDirect,0,$buyPack,$user[1],$ParainDirect,0,$Beclas->phpDate()));$req=$tams->prepare('INSERT INTO _admin_historique_user (id_hu, user, emai, ip ,type, messag,lu,dates ) 
                                                VALUES (?,?,?,?,?,?,?,NOW()) ');$inser=$req->execute(array($user[0],$ParainDirect,$ParainInDirect,$_SERVER["REMOTE_ADDR"],"ACHAT PACK",$user[1].", a acheté le pack (".$buyPack.") . Parrain direct:".$ParainDirect.". Parrain indirect:".$ParainInDirect." _(TABLEAU BORD)",0));$result="true";}else{$req=$tams->prepare('INSERT INTO _admin_bank  (some_bk, somepd_bk, somepi_bk, pack_bk, user_bk,	padirect_bk,	paindirect_bk,	datephp_bk,	datesql_bk ) 
                                                VALUES (?,?,?,?,?,?,?,?,NOW()) ');$inser=$req->execute(array($money,0,0,$buyPack,$user[1],'no','no',$Beclas->phpDate()));$req=$tams->prepare('INSERT INTO _admin_historique_user (id_hu, user, emai, ip ,type, messag,lu,dates ) 
                                                VALUES (?,?,?,?,?,?,?,NOW()) ');$inser=$req->execute(array($user[0],$user[1],"---",$_SERVER["REMOTE_ADDR"],"OFFRE PACK",$_SESSION['pseu'].", a offert le pack (".$nivo[3].") à ".$user[1].". Parrain direct:---. Parrain indirect:--- _(TABLEAU BORD)",0));$result="true";}$Beclas->echoo1(1,"Successfully saved");$Beclas->notify($tams,$_SESSION['id_admin'],$_SESSION['pseu'],"A ajouter, Achat ".$nivo[1],$user[1]);$req=$tams->prepare('INSERT INTO user_notification  (id_user_noti,	lu_noti, suj_noti, desc_noti, someout_noti, somenew_noti, phpdate_noti,	sqldate_noti ) 
									 VALUES (?,?,?,?,?,?,?,NOW()) ');$inser=$req->execute(array($user[0],0,"Offre","Facop vous à offer le pack formation (".$nivo[3].") ",0,0,$Beclas->phpDate()));}else{$Beclas->echoo1(0,"ERROR: contact the developer");$Beclas->notify($tams,$_SESSION['id_admin'],$_SESSION['pseu'],"Added, Classe: Matière ",$_POST['nom']);}}else{$Beclas->echoo1(2,"INFO: élément déja enregistré, existant");}}else{$Beclas->echoo1(0,"ERROR: Veuillez completer correctement tous les champs");} ?>